[phases.setup]
nixPkgs = ["python3", "gcc", "chromium", "chromedriver"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "python app.py"
